language: node_js
node_js:
  - 12.5.0
before_script:
  - npm install
  - npm run build
script: echo "npm test temporarily disabled"
branches:
  only:
    - master
    - develop
deploy:
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(develop|master)
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: "$AWS_BUCKET_NAME"
  skip_cleanup: true
  region: "us-east-1"
  acl: public_read
  local_dir: build
